#!/bin/bash
#$ -N np
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 5

CPU=5
DATASET=$JOB_NAME   # np or yeast, for now. possibly add polio in near future.
BATCHFILE=globalDNDS_${DATASET}.bf

source ~/.bash_profile

# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator/src
SCRIPTDIR=/home/sjs3495/Omega_MutSel/simulation_scripts
WDIR=/share/WilkeLab/work/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME

mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

# Copy files
cp /home/sjs3495/Omega_MutSel/trees/10.tre tree.tre
cp /home/sjs3495/Omega_MutSel/simulation_scripts/run_np.py .
cp /home/sjs3495/Omega_MutSel/simulation_scripts/${DATASET}_codon_eqfreqs.txt .
cp /home/sjs3495/Omega_MutSel/simulation_scripts/functions_simandinf.py .

#Hyphy
cp /home/sjs3495/bin/bin/HYPHYMP .
cp /home/sjs3495/Omega_MutSel/SelectionInference/hyphy/$BATCHFILE .
cp /home/sjs3495/Omega_MutSel/SelectionInference/hyphy/GY94_Header.ibf .
cp /home/sjs3495/Omega_MutSel/SelectionInference/hyphy/matrices_raw.mdl .

# Run
module load python
python run_np.py $SGE_TASK_ID tree.tre $SIMDIR $CPU $DATASET $BATCHFILE

# Cleanup
mkdir -p $RDIR
cp params* $RDIR
cp seqs* $RDIR
rm -rf $WDIR
