#!/bin/bash
#$ -N np
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-498:1
#$ -pe serial 8

CPU=8
DATASET=$JOB_NAME   # np or yeast, for now. possibly add polio in near future.
BATCHFILE=globalDNDS_${DATASET}.bf
FNUCFILE=Fnuc_${DATASET}.mdl

source ~/.bash_profile

# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator/src
SCRIPTDIR=/home/sjs3495/Omega_MutSel/simulation_scripts
WDIR=/share/WilkeLab/work/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/share/WilkeLab/work/sjs3495/Omega_MutSel_rawdata/${DATASET}

mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

#cp $RDIR/seqs${SGE_TASK_ID}.fasta .

# Copy scripts, data files
cp /home/sjs3495/Omega_MutSel/simulation_scripts/run_nyp.py .
cp /home/sjs3495/Omega_MutSel/simulation_scripts/functions_simandinf.py .
cp /home/sjs3495/Omega_MutSel/experimental_data/${DATASET}_codon_eqfreqs.txt .

# Copy hyphy executable, files
cp /home/sjs3495/bin/bin/HYPHYMP .
cp /home/sjs3495/Omega_MutSel/hyphy_files/CF3x4.bf .
cp /home/sjs3495/Omega_MutSel/hyphy_files/GY94.mdl .
cp /home/sjs3495/Omega_MutSel/hyphy_files/$BATCHFILE batchfile.bf
cp /home/sjs3495/Omega_MutSel/hyphy_files/$FNUCFILE fnuc.mdl

# Run
module load python
python run_nyp.py $SGE_TASK_ID $SIMDIR $CPU $DATASET

# Cleanup
mkdir -p $RDIR
cp params* $RDIR
cp seqs* $RDIR
rm -rf $WDIR
