
#!/bin/bash
#$ -N siminf
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 14


source ~/.bash_profile

CPU=14
NUMAA=7
FINALFILE=mutsel-$JOB_NAME-$NUMAA.txt

# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator/src
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/Out_Omega_MutSel/$JOB_NAME-$JOB_ID-$NUMAA

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy files
cp -r $SIMDIR .
cp /home/sjs3495/Omega_MutSel/cluster_scripts/simulate_and_infer_cluster.py .
cp /home/sjs3495/Omega_MutSel/scripts/*.py .


# cp hyphy, paml
cp /home/sjs3495/Omega_MutSel/SelectionInference/* .
cp /home/sjs3495/bin/bin/HYPHYMP .
cp /home/sjs3495/bin/codeml .

# Run
module load python
python simulate_and_infer_cluster.py $CPU $RDIR $FINALFILE $SGE_TASK_ID $NUMAA

# Cleanup
cp *.fasta $RDIR
cp *.tre $RDIR
cp *.bf $RDIR
cp *.log $RDIR
cp mutsel_* $RDIR
rm -rf $WDIR
