#!/bin/bash
#$ -N siminf_paml
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-1:1


source ~/.bash_profile

# INPUT ARGS VARIABLES
MU=1e-5
BL=0.01
SEQLEN=5000


# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator/src
SCRIPTDIR=/home/sjs3495/Omega_MutSel/cluster_scripts
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME

mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

# Copy files
cp /home/sjs3495/Omega_MutSel/cluster_scripts/run_siminf_paml.py .
cp /home/sjs3495/Omega_MutSel/cluster_scripts/functions_simandinf.py .

# Paml
cp /home/sjs3495/bin/codeml .
cp /home/sjs3495/bin/yn00 .
cp /home/sjs3495/Omega_MutSel/SelectionInference/paml/codeml_raw.txt .
cp /home/sjs3495/Omega_MutSel/SelectionInference/paml/yn00.ctl .


# Run
module load python
python run_siminf_paml.py $SGE_TASK_ID MU $BL $SEQLEN $SIMDIR

# Cleanup
mkdir -p $RDIR
cp params* $RDIR
#cp seqs* $RDIR
#cp codonFreqs* $RDIR
rm -rf $WDIR
