
#!/bin/bash
#$ -N siminf_2aa
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-1:1
#$ -pe serial 15


source ~/.bash_profile

CPU=14
FINALFILE=mutsel-$JOB_NAME.txt

# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator/src
THINGSDIR=/home/sjs3495/Omega_MutSel/cluster
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME-$JOB_ID

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy files
cp -r $SIMDIR .
cp /home/sjs3495/Omega_MutSel/cluster_scripts/simulate_and_infer_cluster.py .
cp /home/sjs3495/Omega_MutSel/scripts/functions_simandinf.py .


# cp hyphy
cp $THINGSDIR/hyphy_files/* .
cp /home/sjs3495/bin/bin/HYPHYMP .

# cp paml
#cp $THINGSDIR/codeml.ctl .
#cp /home/sjs3495/bin/codeml .

# Run
module load python
python simulate_and_infer_cluster.py $CPU $RDIR $FINALFILE

# Cleanup
cp *.fasta $RDIR
cp mutsel_* $RDIR
rm -rf $WDIR
