#!/bin/bash
#$ -N conv
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-200:1
#$ -pe serial 1

CPU=1

source ~/.bash_profile


# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator/src
SCRIPTDIR=/home/sjs3495/Omega_MutSel/scripts/simulation_scripts
WDIR=/share/WilkeLab/work/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME

mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

# Copy scripts
cp /home/sjs3495/Omega_MutSel/scripts/simulation_scripts/run_convergence.py .
cp /home/sjs3495/Omega_MutSel/scripts/simulation_scripts/functions_simandinf.py .

# Copy Hyphy executable, files
cp /home/sjs3495/bin/bin/HYPHYMP .
cp /home/sjs3495/Omega_MutSel/hyphy_files/GY94.mdl .
cp /home/sjs3495/Omega_MutSel/hyphy_files/globalDNDS_fequal.bf .

# Run
module load python
python run_convergence.py $SGE_TASK_ID $SIMDIR $CPU

# Cleanup
mkdir -p $RDIR
cp params* $RDIR
cp seqs* $RDIR
cp codonFreqs* $RDIR
rm -rf $WDIR
