#!/bin/bash
#$ -N gpcrs
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-533:1
#$ -pe serial 8
CPU=7

source ~/.bash_profile



# Set up directories
SEQDIR=/home/sjs3495/hyin
SCRIPTDIR=/home/sjs3495/Omega_MutSel/gpcr_scripts
WDIR=/share/WilkeLab/work/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME

mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

# Copy scripts
cp /home/sjs3495/hyin/gpcr${SGE_TASK_ID}.fasta .
cp /home/sjs3495/Omega_MutSel/gpcr_scripts/* .
cp /home/sjs3495/Omega_MutSel/hyphy_files/CF3x4.bf .
cp /home/sjs3495/Omega_MutSel/hyphy_files/GY94.mdl .
cp /home/sjs3495/Omega_MutSel/hyphy_files/globalDNDS_gpcr.bf .
cp /home/sjs3495/bin/bin/HYPHYMP .

# Run
module load python
python run_gpcrs.py $SGE_TASK_ID $CPU

# Cleanup
mkdir -p $RDIR
cp output* $RDIR
rm -rf $WDIR
