#!/bin/bash
#$ -N gpcr_M0_again
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-1:1

source ~/.bash_profile



# Set up directories
SEQDIR=/home/sjs3495/hyin
SIMDIR=/home/sjs3495/MutSel/Simulator/src
SCRIPTDIR=/home/sjs3495/Omega_MutSel/gpcr_scripts
WDIR=/share/WilkeLab/work/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME

mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

# Copy scripts
cp $SEQDIR/gpcr${SGE_TASK_ID}.fasta .
cp $SCRIPTDIR/* .
cp /home/sjs3495/bin/bin/HYPHYMP .
cp /home/sjs3495/Omega_MutSel/hyphy_files/GY94.mdl .

# Run
module load python
python run_gpcrs.py $SGE_TASK_ID $SIMDIR

# Cleanup
mkdir -p $RDIR
cp outfile* $RDIR
cp batchfile.bf $RDIR
rm -rf $WDIR
